"""initial schema

Revision ID: bf89724fd3f7
Revises: 
Create Date: 2026-08-29 14:09:13.254044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf89724fd3f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('product', sa.String(length=64), nullable=True),
    sa.Column('authority', sa.String(length=16), nullable=False),
    sa.Column('contractual', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_documents_policy_id'), 'documents', ['policy_id'], unique=False)
    op.create_table('query_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_requests')
    op.drop_index(op.f('ix_documents_policy_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
